export const {
	DB,
	DB_USER,
	DB_PASS,
	PUSHER_SECRET,
	PUSHER_APP_ID,
	NEXT_PUBLIC_PUSHER_KEY,
	NEXT_PUBLIC_PUSHER_CLUSTER,
	MAYTAPI_PHONE_ID,
	MAYTAPI_PRODUCT_ID,
	MAYTAPI_API_TOKEN,
} = process.env;
